repos:
  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports
        exclude: ^(pre_commit/resources/|testing/resources/python3_hooks_repo/)
        args: [--py39-plus]

  - repo: local
    hooks:
      - id: run-lint
        name: Run lint.py
        entry: python ./Scripts/lint.py
        language: system
        types: [python]